language: node_js
node_js:
  - '0.12'
  - '6.2.0'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
matrix:
  fast_finish: true
before_script:
  - npm install -g grunt-cli
services: mongodb
